### ISSUE TITLE
Changer le texte et le style du bouton "Export"

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/decp.info#6]
```css
.export {
font-size: 0;
}
.export:before { content: “Your rext here”; font-size: 20px; }
```

https://community.plotly.com/t/styling-the-export-button-in-datatable/38798/13
